### ISSUE TITLE
Developer API

### ISSUE THREAD

**Issue by Michael21107** [justalemon/DumpsterDiving#8]
### What idea do you have in mind?

allow devs to add items, along with chances of specific ones (both actual items and ''text only'' ones) in particular dumpsters and random items in any dumpsters

### What would be the purpose of this feature?

could allow LSPDFR (police mod) callout (police missions) devs to add evidence in dumpsters near crime scenes

**Comment by Michael21107** [comment]
NOTE: I didn't add any labels

**Comment by justalemon** [comment]
Yep, this is automatic so I know which issues I have taken a look at and which ones need to be reviewed.

**Comment by Michael21107** [comment]
> Yep, this is automatic so I know which issues I have taken a look at and which ones need to be reviewed.

wouldn't it be better then to make a tag like ''status: pending'' and add that automatically?

**Comment by justalemon** [comment]
That's what p4 means, unless is marked as invalid.

**Comment by Michael21107** [comment]
I figured that out now but I don't think that all issues should be marked as acknowledged by default (since they won't be for a while)
